# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend CI

on:
  push:
    branches:
      - '*'
    paths: 
      - "!frontend/**"
      - "backend/**"

defaults:
  run:
    working-directory: backend

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Current folder
        run: |
         echo "Backend Change trigger"
         ls -al
