# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches:
      - 'main'
      - 'ci-test/*'
    paths: 
      - "frontend/**"
      - "!backend/**"

defaults:
  run:
    working-directory: frontend

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependency
        run: git fetch --unshallow --tags
      - name: Use Node.js 16.14.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.x
      - name: Run Install & build
        run : |
          npm i 
          npm run build-storybook
          ls -al
